export default {
    products: [
        {
            _id: "1",
            name: "Avocado",
            category: "Fruits",
            image: "./images/fruits/avocado.svg",
            price: 3.99,
            rating: 5.0,
            numReviews: 12,
            quantityInStock: 20,
            unitMeasure: "kg",
            description: "Mexican avocado.",
            Ingredients: "Water, fat, carbohydrates, and  protein",
            Benefits: "High levels of healthy, beneficial fats, which can help a person feel fuller between meals. Eating fat slows the breakdown of carbohydrates, which helps keep blood sugar levels stable.",
        },
        {
            _id: "2",
            name: "Coca Cola",
            category: "Drinks",
            image: "./images/drinks/cocacola.svg",
            price: 2.69,
            rating: 3.2,
            numReviews: 34,
            quantityInStock: 67,
            unitMeasure: "L",
        },
        {
            _id: "3",
            name: "Broccoli",
            category: "Vegetables",
            image: "./images/vegetables/broccoli.svg",
            price: 3.99,
            rating: 3.9,
            numReviews: 12,
            quantityInStock: 0,
            unitMeasure: "kg",
            description: "Some desciption goes here for broccoli like advantages and ingredients",
        },
        {
            _id: "4",
            name: "Banana",
            category: "Fruits",
            image: "./images/fruits/bananas.svg",
            price: 1.59,
            rating: 3.9,
            numReviews: 40,
            quantityInStock: 280,
            unitMeasure: "kg",
            description: "Cavendish banana. Ingredients: no fat, protein, carbohydrate, sugar, fiber, and potassium. Benefits: rich in nutrients, may improve blood sugar levels, may support digestive health, may aid weight loss, may support heart health.",
        },
        {
            _id: "5",
            name: "Coffee",
            category: "Drinks",
            image: "./images/drinks/coffee.svg",
            price: 1.27,
            rating: 4.1,
            numReviews: 23,
            quantityInStock: 401,
            unitMeasure: "L",
        },
        {
            _id: "6",
            name: "Cauliflower",
            category: "Vegetables",
            image: "./images/vegetables/cauliflower.svg",
            price: 5.99,
            rating: 1.9,
            numReviews: 47,
            quantityInStock: 100,
            unitMeasure: "kg",
        },
        {
            _id: "7",
            name: "Cherry",
            category: "Fruits",
            image: "./images/fruits/cherry.svg",
            price: 2.0,
            rating: 4.5,
            numReviews: 30,
            quantityInStock: 202,
            unitMeasure: "kg",
        },
        {
            _id: "8",
            name: "Fanta",
            category: "Drinks",
            image: "./images/drinks/fanta.svg",
            price: 2.49,
            rating: 3.8,
            numReviews: 41,
            quantityInStock: 334,
            unitMeasure: "L",
        },
        {
            _id: "9",
            name: "Cucumber",
            category: "Vegetables",
            image: "./images/vegetables/cucumber.svg",
            price: 1.29,
            rating: 3.5,
            numReviews: 21,
            quantityInStock: 312,
            unitMeasure: "kg",
        },
        {
            _id: "10",
            name: "Coconut",
            category: "Fruits",
            image: "./images/fruits/coconut.svg",
            price: 2.49,
            rating: 5.0,
            numReviews: 49,
            quantityInStock: 309,
            unitMeasure: "kg",
        },
        {
            _id: "11",
            name: "Hot chocolate",
            category: "Drinks",
            image: "./images/drinks/hotchocolate.svg",
            price: 3.99,
            rating: 2.9,
            numReviews: 37,
            quantityInStock: 102,
            unitMeasure: "L",
        },
        {
            _id: "12",
            name: "Eggplant",
            category: "Vegetables",
            image: "./images/vegetables/eggplant.svg",
            price: 2.29,
            rating: 4.0,
            numReviews: 47,
            quantityInStock: 209,
            unitMeasure: "kg",
        },
        {
            _id: "13",
            name: "Fig",
            category: "Fruits",
            image: "./images/fruits/fig.svg",
            price: 3.09,
            rating: 4.6,
            numReviews: 34,
            quantityInStock: 207,
            unitMeasure: "kg",
        },
        {
            _id: "14",
            name: "Ice Tea",
            category: "Drinks",
            image: "./images/drinks/icetea.svg",
            price: 1.99,
            rating: 3.7,
            numReviews: 42,
            quantityInStock: 399,
            unitMeasure: "L",
        },
        {
            _id: "15",
            name: "Lettuce",
            category: "Vegetables",
            image: "./images/vegetables/lettuce.svg",
            price: 2.69,
            rating: 3.1,
            numReviews: 19,
            quantityInStock: 309,
            unitMeasure: "kg",
        },
        {
            _id: "16",
            name: "Kiwi",
            category: "Fruits",
            image: "./images/fruits/kiwi.svg",
            price: 3.4,
            rating: 4.5,
            numReviews: 39,
            quantityInStock: 0,
            unitMeasure: "kg",
        },
        {
            _id: "17",
            name: "Lemonade",
            category: "Drinks",
            image: "./images/drinks/lemonade.svg",
            price: 3.19,
            rating: 2.9,
            numReviews: 34,
            quantityInStock: 36,
            unitMeasure: "L",
        },
        {
            _id: "18",
            name: "Melon",
            category: "Vegetables",
            image: "./images/vegetables/melon.svg",
            price: 1.3,
            rating: 4.4,
            numReviews: 48,
            quantityInStock: 267,
            unitMeasure: "kg",
        },
        {
            _id: "19",
            name: "Lemon",
            category: "Fruits",
            image: "./images/fruits/lemon.svg",
            price: 1.79,
            rating: 3.2,
            numReviews: 45,
            quantityInStock: 100,
            unitMeasure: "kg",
        },
        {
            _id: "20",
            name: "Milk",
            category: "Drinks",
            image: "./images/drinks/milk.svg",
            price: 2.79,
            rating: 4.1,
            numReviews: 21,
            quantityInStock: 199,
            unitMeasure: "L",
        },
        {
            _id: "21",
            name: "Mushroomn",
            category: "Vegetables",
            image: "./images/vegetables/mushroom.svg",
            price: 2.99,
            rating: 2.8,
            numReviews: 31,
            quantityInStock: 178,
            unitMeasure: "kg",
        },
        {
            _id: "22",
            name: "Mango",
            category: "Fruits",
            image: "./images/fruits/mango.svg",
            price: 4.99,
            rating: 4.7,
            numReviews: 23,
            quantityInStock: 223,
            unitMeasure: "kg",
        },
        {
            _id: "23",
            name: "Milk Shake",
            category: "Drinks",
            image: "./images/drinks/milkshake.svg",
            price: 4.29,
            rating: 2.8,
            numReviews: 24,
            quantityInStock: 303,
            unitMeasure: "L",
        },
        {
            _id: "24",
            name: "Olives",
            category: "Vegetables",
            image: "./images/vegetables/olives.svg",
            price: 3.59,
            rating: 3.5,
            numReviews: 41,
            quantityInStock: 399,
            unitMeasure: "kg",
        },
        {
            _id: "25",
            name: "Orange",
            category: "Fruits",
            image: "./images/fruits/oranges.svg",
            price: 5.59,
            rating: 2.6,
            numReviews: 43,
            quantityInStock: 401,
            unitMeasure: "kg",
        },
        {
            _id: "26",
            name: "Mojito",
            category: "Drinks",
            image: "./images/drinks/mojito.svg",
            price: 3.99,
            rating: 4.1,
            numReviews: 38,
            quantityInStock: 309,
            unitMeasure: "L",
        },
        {
            _id: "27",
            name: "Peas",
            category: "Vegetables",
            image: "./images/vegetables/peas.svg",
            price: 5.99,
            rating: 2.8,
            numReviews: 23,
            quantityInStock: 400,
            unitMeasure: "kg",
        },
        {
            _id: "28",
            name: "Papaya",
            category: "Fruits",
            image: "./images/fruits/papaya.svg",
            price: 8.99,
            rating: 3.8,
            numReviews: 39,
            quantityInStock: 131,
            unitMeasure: "kg",
        },
        {
            _id: "29",
            name: "Orange Juice",
            category: "Drinks",
            image: "./images/drinks/orangejuice.svg",
            price: 2.99,
            rating: 2.5,
            numReviews: 18,
            quantityInStock: 109,
            unitMeasure: "L",
        },
        {
            _id: "30",
            name: "Radish",
            category: "Vegetables",
            image: "./images/vegetables/radish.svg",
            price: 2.99,
            rating: 4.0,
            numReviews: 50,
            quantityInStock: 295,
            unitMeasure: "kg",
        },
        {
            _id: "31",
            name: "Pineapple",
            category: "Fruits",
            image: "./images/fruits/pineapple.svg",
            price: 3.69,
            rating: 2.1,
            numReviews: 20,
            quantityInStock: 222,
            unitMeasure: "kg",
        },
        {
            _id: "32",
            name: "Pomogranate Juice",
            category: "Drinks",
            image: "./images/drinks/pomegranatejuice.svg",
            price: 2.99,
            rating: 3.0,
            numReviews: 30,
            quantityInStock: 346,
            unitMeasure: "L",
        },
        {
            _id: "33",
            name: "Tomato",
            category: "Vegetables",
            image: "./images/vegetables/tomato.svg",
            price: 1.1,
            rating: 2.4,
            numReviews: 49,
            quantityInStock: 491,
            unitMeasure: "kg",
        },
        {
            _id: "34",
            name: "Strawberry",
            category: "Fruits",
            image: "./images/fruits/strawberry.svg",
            price: 2.9,
            rating: 3.0,
            numReviews: 39,
            quantityInStock: 444,
            unitMeasure: "kg",
        },
        {
            _id: "35",
            name: "Water",
            category: "Drinks",
            image: "./images/drinks/water.svg",
            price: 0.3,
            rating: 4.4,
            numReviews: 50,
            quantityInStock: 496,
            unitMeasure: "L",
        },
        {
            _id: "36",
            name: "Watermelon",
            category: "Vegetables",
            image: "./images/vegetables/watermelon.svg",
            price: 2.0,
            rating: 4.9,
            numReviews: 19,
            quantityInStock: 306,
            unitMeasure: "kg",
        },
    ]
};